services:
  news-service:
    build: ./news-service
    ports:
      - "8003:8003"
    env_file:
      - ./news-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - lif-network

  sasb-service:
    build: ./sasb-service
    ports:
      - "8004:8004"
    env_file:
      - ./sasb-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - lif-network

  issuepool-service:
    build: ./issuepool-service
    ports:
      - "8005:8005"
    env_file:
      - ./issuepool-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - lif-network

  report-service:
    build: ./report-service
    ports:
      - "8006:8006"
    env_file:
      - ./report-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - lif-network

  stock-service:
    build: ./stock-service
    ports:
      - "8007:8007"
    env_file:
      - ./stock-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - lif-network

  thesis-service:
    build: ./thesis-service
    ports:
      - "8008:8008"
    env_file:
      - ./thesis-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - lif-network

  gri-service:
    build: ./gri-service
    ports:
      - "8010:8010"
    env_file:
      - ./gri-service/.env
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=0
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - lif-network
  
  # =========================================================
  #               수정된 Gateway 서비스 부분
  # =========================================================
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    # env_file을 추가하여 ./gateway/.env 파일의 변수들을 로드합니다.
    env_file:
      - ./gateway/.env
    # environment 섹션에서는 .env 파일에 없는 변수나, 
    # .env 파일의 값을 참조하는 변수만 남깁니다.
    # 하드코딩된 민감 정보들은 모두 제거했습니다.
    environment:
      - PYTHONUNBUFFERED=1
      # 아래 변수들은 .env 파일에서 자동으로 로드됩니다.
      # - NEWS_SERVICE_URL=${NEWS_SERVICE_URL}
      # - SASB_SERVICE_URL=${SASB_SERVICE_URL}
      # ... (나머지 서비스 URL)
      # - DB_HOST=${DB_HOST}
      # ... (나머지 DB 정보)
      # - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      # - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
    depends_on:
      - news-service
      - sasb-service
      - issuepool-service
      - report-service
      - stock-service
      - thesis-service
      - gri-service
    networks:
      - lif-network
  # =========================================================
  #                        수정 끝
  # =================================_========================

networks:
  lif-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
        - subnet: 172.20.0.0/16