apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway:local
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres:5432/lifdb"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: NEWS_SERVICE_URL
          value: "http://news-service:8003"
        - name: SASB_SERVICE_URL
          value: "http://sasb-service:8004"
        - name: ISSUEPOOL_SERVICE_URL
          value: "http://issuepool-service:8005"
        - name: REPORT_SERVICE_URL
          value: "http://report-service:8006"
        - name: STOCK_SERVICE_URL
          value: "http://stock-service:8007"
        - name: THESIS_SERVICE_URL
          value: "http://thesis-service:8008"
        - name: SERVICE_NAME
          value: "gateway"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
